export const PaygateConstants = {
  PAYGATE_TRANSACTION_NOT_DONE : "0",
  PAYGATE_TRANSACTION_APPROVED : "1",
  PAYGATE_TRANSACTION_DECLINED : "2",
  PAYGATE_TRANSACTION_CANCELLED : "3",
  PAYGATE_TRANSACTION_USER_CANCELLED : "4"
}
